# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
# Set Windows Settings
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Revert taskbar settings
        allowPrerelease: true
      settings:
        Alignment: Middle # [KeepCurrentValue, Left]
        HideLabelsMode: Always # [KeepCurrentValue, WhenFull, Never]
        SearchBoxMode: Hide # [KeepCurrentValue, ShowIconOnly, SearchBox, ShowIconAndLabel]
        TaskViewButton: Hide # [KeepCurrentValue, Show]
        WidgetsButton: Hide # [KeepCurrentValue, Show]
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for `HideLabelsMode`.
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Revert Windows Explorer settings
        allowPrerelease: true
      settings:
        FileExtensions: Show # [KeepCurrentValue, Hide]
        HiddenFiles: Show # [KeepCurrentValue, Hide]
        ItemCheckBoxes: Show # [KeepCurrentValue, Hide]
        RestartExplorer: # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for all WindowsExplorer settings.
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Hide seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Present
        # Use caution when setting `RestartExplorer: true` as this will force explorer to close.
        RestartExplorer: true # Required to apply changes
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        id: Git.Git
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Yarn
        allowPrerelease: true
      settings:
        id: Yarn.Yarn
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Python 3.10
        allowPrerelease: true
      settings:
        id: Python.Python.3.10
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Node.js LTS
        allowPrerelease: true
      settings:
        id: OpenJS.NodeJS.LTS
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK 8.0-preview
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.Preview
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        id: Docker.DockerDesktop
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Git LFS
        allowPrerelease: true
      settings:
        id: GitHub.GitLFS
        source: winget
# Install Development Applications
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install PowerShell 7
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Enterprise
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Enterprise
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VSCode
      directives:
        description: Install Visual Studio Code
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage.Preview
      directives:
        description: Install Visual Studio 2022 Enterprise Preview
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Enterprise.Preview
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      dependsOn:
        - vsPackage
        - vsPackage.Preview
      directives:
        description: Install required VS workloads
        allowPrerelease: true
      settings:
        # https://learn.microsoft.com/visualstudio/install/workload-and-component-ids
        productId: Microsoft.VisualStudio.Product.Enterprise
        channelId: VisualStudio.17.Release
        vsConfigFile: '${WinGetConfigRoot}\..\.vsconfig'
# Install additional Dev/Debug Applications
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: gitkraken
      directives:
        description: Install GitKraken
        allowPrerelease: true
      settings:
        id: Axosoft.GitKraken
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ilSpy
      directives:
        description: Install ILSpy
        allowPrerelease: true
      settings:
        id: icsharpcode.ILSpy
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: msbuildSLV
      directives:
        description: Install MSBuild Structured Log Viewer
        allowPrerelease: true
      settings:
        id: KirillOsenkov.MSBuildStructuredLogViewer
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: windowsTerminal
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsTerminal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ssms
      directives:
        description: Install SSMS
        allowPrerelease: true
      settings:
        id: Microsoft.SQLServerManagementStudio
        source: winget
# Utilities
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: screenToGif
      directives:
        description: Install ScreenToGif
        allowPrerelease: true
      settings:
        id: NickeManarin.ScreenToGif
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Everything
        allowPrerelease: true
      settings:
        id: voidtools.Everything
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Kleopatra
        allowPrerelease: true
      settings:
        id: GnuPG.Gpg4win
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Github CLI
        allowPrerelease: true
      settings:
        id: GitHub.cli
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install NuGet Package Explorer
        allowPrerelease: true
      settings:
        id: 9WZDNCRDMDM3
        source: msstore
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Firefox
        allowPrerelease: true
      settings:
        id: Mozilla.Firefox
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Brave
        allowPrerelease: true
      settings:
        id: Brave.Brave
        source: winget
# Stream/Presentation
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: obsStudio
      directives:
        description: Install OBS Studio
        allowPrerelease: true
      settings:
        id: OBSProject.OBSStudio
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: zoomit
      directives:
        description: Install Zoomit
        allowPrerelease: true
      settings:
        id: Microsoft.Sysinternals.ZoomIt
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: carnac
      directives:
        description: Install Carnac
        allowPrerelease: true
      settings:
        id: code52.Carnac
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sharex
      directives:
        description: Install ShareX
        allowPrerelease: true
      settings:
        id: ShareX.ShareX
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: powertoys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget
  configurationVersion: 0.2.0
