# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
# Set Windows Settings
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
# Install Apps
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Brave
        allowPrerelease: true
      settings:
        id: Brave.Brave
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Joplin
        allowPrerelease: true
      settings:
        id: Joplin.Joplin
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Thunderbird
        allowPrerelease: true
      settings:
        id: Mozilla.Thunderbird
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Proton Mail Bridge
        allowPrerelease: true
      settings:
        id: ProtonTechnologies.ProtonMailBridge
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Proton VPN
        allowPrerelease: true
      settings:
        id: ProtonTechnologies.ProtonVPN
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Cryptomator
        allowPrerelease: true
      settings:
        id: Cryptomator.Cryptomator
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Powertoys
        allowPrerelease: true
      settings:
        id: Microsoft.PowerToys
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Spotify
        allowPrerelease: true
      settings:
        id: Spotify.Spotify
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install ZeroTier
        allowPrerelease: true
      settings:
        id: ZeroTier.ZeroTierOne
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Digikam
        allowPrerelease: true
      settings:
        id: KDE.digikam
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Gimp
        allowPrerelease: true
      settings:
        id: GIMP.GIMP
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install LibreOffice
        allowPrerelease: true
      settings:
        id: TheDocumentFoundation.LibreOffice
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Signal
        allowPrerelease: true
      settings:
        id: OpenWhisperSystems.Signal
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Nvidia Broadcast
        allowPrerelease: true
      settings:
        id: Nvidia.Broadcast
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Fan Control
        allowPrerelease: true
      settings:
        id: Rem0o.FanControl
        source: winget
  configurationVersion: 0.2.0