# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: OsVersion
      directives:
        description: Verify min OS version requirement
        module: Microsoft.Windows.Developer
        allowPrerelease: true
      settings:
        MinVersion: 10.0.19041 # WinGet (Windows Package Manager) requires a minimum of Windows 10, version 1809 or newer.
  resources:
    - resource: DeveloperMode
      directives:
        description: Enable Developer Mode
        module: Microsoft.Windows.Developer
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Enterprise
        module: Microsoft.WinGet.DSC
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Enterprise
        source: winget
    - resource: WinGetPackage
      id: vsPackage
      directives:
        description: Install VSCode
        module: Microsoft.WinGet.DSC
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
    - resource: InstallVSConfig
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads
        module: Microsoft.VisualStudio.DSC
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Enterprise
        channelId: VisualStudio.17.Release
        vsconfigFile: ${WinGetConfigRoot}\..\.vsconfig
  configurationVersion: 0.2.0